# Site settings
title: The Robinson Lab | Welcome
description: 
url: "jfrobinson.github.io"
author:
  name: "Joshua Robinson"
  email: "Joshua.Robinson@ucsf.edu"
  url: "jfrobinson.github.io

# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
